language: node_js
cache: yarn

notifications:
  email: false

node_js:
  - "8"

script:
  - yarn lint
  - yarn test
  - yarn build

after_success:
  - yarn semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
